repos:
#- repo: https://github.com/pre-commit/pre-commit-hooks
#  rev: v2.3.0
#  hooks:
#  - id: check-yaml
#  - id: end-of-file-fixer
#  - id: trailing-whitespace

- repo: https://github.com/DevinR528/cargo-sort
  rev: v1.0.9
  hooks:
  - id: cargo-sort
    args: ["dscoursework-backend/Cargo.toml"]
