/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivilegeRequest {
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "price")]
    pub price: i32,
    #[serde(rename = "ticket_uid")]
    pub ticket_uid: uuid::Uuid,
    #[serde(rename = "paidFromBalance")]
    pub paid_from_balance: bool,
}

impl PrivilegeRequest {
    pub fn new(username: String, price: i32, ticket_uid: uuid::Uuid, paid_from_balance: bool) -> PrivilegeRequest {
        PrivilegeRequest {
            username,
            price,
            ticket_uid,
            paid_from_balance,
        }
    }
}
