apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: rsoi
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: "{{ .Values.service.image.version }}"
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: micro-services
    app.kubernetes.io/managed-by: helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/version: "{{ .Values.service.image.version }}"
        app.kubernetes.io/component: application
        app.kubernetes.io/part-of: micro-services
        app.kubernetes.io/managed-by: helm
    spec:
      containers:
        - name: gateway
          image: squeakbug73/gateway-service:0.1
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
          env:
          - name: KAFKA__BOOTSTRAP_SERVERS
            valueFrom:
              configMapKeyRef:
                name: gateway-config
                key: KAFKA__BOOTSTRAP_SERVERS
          - name: GATEWAY_SERVICE__LISTEN_PORT
            valueFrom:
              configMapKeyRef:
                name: gateway-config
                key: LISTEN_PORT
          - name: RABBIT_MQ_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: gateway-config
                key: RABBIT_MQ_ADDRESS
          - name: BONUS_SERVICE_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: gateway-config
                key: BONUS_SERVICE_ADDRESS
          - name: FLIGHT_SERVICE_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: gateway-config
                key: FLIGHT_SERVICE_ADDRESS
          - name: TICKET_SERVICE_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: gateway-config
                key: TICKET_SERVICE_ADDRESS
          - name: IDENTITY_SECRET_KEY
            valueFrom:
              configMapKeyRef:
                name: gateway-config
                key: IDENTITY_SECRET_KEY
