apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: rsoi
data:
  LISTEN_PORT:
    "8080"
  RABBIT_MQ_ADDRESS:
    "amqp://rmq:rmq@147.45.166.216:5672/%2f"
  BONUS_SERVICE_ADDRESS:
    "http://squeakbug-rsoi.com:8050"
  FLIGHT_SERVICE_ADDRESS:
    "http://squeakbug-rsoi.com:8060"
  TICKET_SERVICE_ADDRESS:
    "http://squeakbug-rsoi.com:8070"
  IDENTITY_SECRET_KEY:
    "my_secret_key"
  KAFKA__BOOTSTRAP_SERVERS:
    "147.45.166.216:9092"