apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: "{{ .Values.service.image.version }}"
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: micro-services
    app.kubernetes.io/managed-by: helm
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/version: "{{ .Values.service.image.version }}"
        app.kubernetes.io/component: application
        app.kubernetes.io/part-of: micro-services
        app.kubernetes.io/managed-by: helm
    spec:
      containers:
        - name: "{{ .Chart.Name }}"
          image: "{{ .Values.service.image.name }}:{{ .Values.service.image.version }}"
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /api/v1/ping
              port: {{ .Values.service.internalPort }}
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          ports:
          - containerPort: {{ .Values.service.internalPort }}
          env:
          - name: KAFKA__BOOTSTRAP_SERVERS
            valueFrom:
              configMapKeyRef:
                name: gateway-config
                key: KAFKA__BOOTSTRAP_SERVERS
          - name: GATEWAY_SERVICE__LISTEN_PORT
            valueFrom:
              configMapKeyRef:
                name: gateway-config
                key: LISTEN_PORT
          - name: RABBIT_MQ_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: gateway-config
                key: RABBIT_MQ_ADDRESS
          - name: BONUS_SERVICE_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: gateway-config
                key: BONUS_SERVICE_ADDRESS
          - name: FLIGHT_SERVICE_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: gateway-config
                key: FLIGHT_SERVICE_ADDRESS
          - name: TICKET_SERVICE_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: gateway-config
                key: TICKET_SERVICE_ADDRESS
          - name: IDENTITY_SECRET_KEY
            valueFrom:
              configMapKeyRef:
                name: gateway-config
                key: IDENTITY_SECRET_KEY
          resources:
            requests:
              cpu: 1
              memory: 512Mi
            limits:
              cpu: 1
              memory: 512Mi