apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: {{ .Values.global.namespace }}
data:
  LISTEN_PORT:
    "{{ .Values.service.internalPort }}"
  RABBIT_MQ_ADDRESS:
    "{{ .Values.global.rmqEndpoint }}"
  BONUS_SERVICE_ADDRESS:
    "http://bonus.{{ .Values.global.namespace }}.svc.cluster.local:8050"
  FLIGHT_SERVICE_ADDRESS:
    "http://flights.{{ .Values.global.namespace }}.svc.cluster.local:8060"
  TICKET_SERVICE_ADDRESS:
    "http://ticket.{{ .Values.global.namespace }}.svc.cluster.local:8070"
  IDENTITY_SECRET_KEY:
    "{{ .Values.global.identitySecretKey }}"
  KAFKA__BOOTSTRAP_SERVERS:
    "{{ .Values.global.kafkaBootstrapServerEndpoint }}"
  AUTHENTIK__JWKS:
    "{{ .Values.global.authentikJWKSEndpoint }}"
  AUTHENTIK__USER_INFO:
    "{{ .Values.global.authentikUserInfoEndpoint }}"
  AUTHENTIK__OPENID_CONFIG:
    "{{ .Values.global.authentikOpenIDConfigEndpoint }}"