apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: rsoi
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: "{{ .Values.service.image.version }}"
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: micro-services
    app.kubernetes.io/managed-by: helm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/version: "{{ .Values.service.image.version }}"
        app.kubernetes.io/component: application
        app.kubernetes.io/part-of: micro-services
        app.kubernetes.io/managed-by: helm
    spec:
      containers:
        - name: flight
          image: squeakbug73/flight-service:0.1
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8060
          env:
          - name: KAFKA__BOOTSTRAP_SERVERS
            valueFrom:
              configMapKeyRef:
                name: flight-config
                key: KAFKA__BOOTSTRAP_SERVERS
          - name: IDENTITY_SECRET_KEY
            valueFrom:
              configMapKeyRef:
                name: flight-config
                key: IDENTITY_SECRET_KEY
          - name: FLIGHT_SERVICE__DATABASE_URL
            valueFrom:
              configMapKeyRef:
                name: flight-config
                key: DATABASE_URL
          - name: FLIGHT_SERVICE__LISTEN_PORT
            valueFrom:
              configMapKeyRef:
                name: flight-config
                key: LISTEN_PORT
