apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: rsoi
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: "{{ .Values.service.image.version }}"
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: micro-services
    app.kubernetes.io/managed-by: helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bonus
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/version: "{{ .Values.service.image.version }}"
        app.kubernetes.io/component: application
        app.kubernetes.io/part-of: micro-services
        app.kubernetes.io/managed-by: helm
    spec:
      containers:
      - name: bonus
        image: squeakbug73/bonus-service:0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8050
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: bonus-config
              key: database-url
        - name: LISTEN_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: bonus-config
              key: listen-address
