apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: "{{ .Values.service.image.version }}"
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: micro-services
    app.kubernetes.io/managed-by: helm
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/version: "{{ .Values.service.image.version }}"
        app.kubernetes.io/component: application
        app.kubernetes.io/part-of: micro-services
        app.kubernetes.io/managed-by: helm
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.service.image.name }}:{{ .Values.service.image.version }}"
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /api/v1/ping
            port: {{ .Values.service.internalPort }}
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 3
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        env:
        - name: KAFKA__BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: ticket-config
              key: KAFKA__BOOTSTRAP_SERVERS
        - name: IDENTITY_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              name: ticket-config
              key: IDENTITY_SECRET_KEY
        - name: TICKET_SERVICE__DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: ticket-config
              key: DATABASE_URL
        - name: TICKET_SERVICE__LISTEN_PORT
          valueFrom:
            configMapKeyRef:
              name: ticket-config
              key: LISTEN_PORT
        resources:
          requests:
            cpu: 1
            memory: 512Mi
          limits:
            cpu: 1
            memory: 512Mi