apiVersion: v1
kind: ConfigMap
metadata:
  name: ticket-config
  namespace: {{ .Values.global.namespace }}
data:
  DATABASE_URL: {{
    printf "postgresql://%s:%s@%s/tickets"
    .Values.global.postgresLogin
    .Values.global.postgresPassword
    .Values.global.postgresEndpoint
  }}
  LISTEN_PORT:
    "{{ .Values.service.internalPort }}"
  IDENTITY_SECRET_KEY:
    "{{ .Values.global.identitySecretKey }}"
  KAFKA__BOOTSTRAP_SERVERS:
    "{{ .Values.global.kafkaBootstrapServerEndpoint }}"