apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name}}
  namespace: rsoi
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: "{{ .Values.service.image.version }}"
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: micro-services
    app.kubernetes.io/managed-by: helm
spec:
  selector:
    app: {{ .Chart.Name }}
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8060
    targetPort: 8060
