apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: rsoi
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: "{{ .Values.service.image.version }}"
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: micro-services
    app.kubernetes.io/managed-by: helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/version: "{{ .Values.service.image.version }}"
        app.kubernetes.io/component: application
        app.kubernetes.io/part-of: micro-services
        app.kubernetes.io/managed-by: helm
    spec:
      containers:
        - name: gateway
          image: squeakbug73/gateway-service:0.1
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
          env:
          - name: LISTEN_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: gateway-config
                key: listen-address
          - name: BONUS_SERVICE_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: gateway-config
                key: bonus-service-address
          - name: FLIGHT_SERVICE_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: gateway-config
                key: flight-service-address
          - name: TICKET_SERVICE_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: gateway-config
                key: ticket-service-address
