apiVersion: v1
kind: ConfigMap
metadata:
  name: bonus-config
  namespace: {{ .Values.global.namespace }}
data:
  DATABASE_URL: {{
    printf "postgresql://%s:%s@%s/privileges"
    .Values.global.postgresLogin
    .Values.global.postgresPassword
    .Values.global.postgresEndpoint
  }}
  LISTEN_PORT:
    "{{ .Values.service.internalPort }}"
  IDENTITY_SECRET_KEY:
    "{{ .Values.global.identitySecretKey }}"
  KAFKA__BOOTSTRAP_SERVERS:
    "{{ .Values.global.kafkaBootstrapServerEndpoint }}"
  AUTHENTIK__JWKS:
    "{{ .Values.global.authentikJWKSEndpoint }}"
  AUTHENTIK__USER_INFO:
    "{{ .Values.global.authentikUserInfoEndpoint }}"
  AUTHENTIK__OPENID_CONFIG:
    "{{ .Values.global.authentikOpenIDConfigEndpoint }}"